const Map<String, Map<String, String>> copy = {
  'en': {
    'personalCare': 'Personal Care',
    'homeTitle': 'Grooming',
    'gearTitle': 'Gear',
    'statsTitle': 'Activity',
    'settingsTitle': 'Settings',
    'welcome': 'Welcome',
    'enterName': 'What is your name?',
    'saveName': 'Continue',
    'bladeLife': 'Blade Life & Shaving',
    'remaining': 'remaining',
    'usesRemaining': 'uses remaining',
    'groomed': 'Groomed',
    'bodyAverage': 'body average',
    'addFirst': 'Add your first gear',
    'bodyMap': 'Body Map',
    'allZones': 'All Zones',
    'bodyQuestion': 'Where are we shaving?',
    'front': 'Front',
    'back': 'Back',
    'fresh': 'Fresh',
    'soon': 'Soon',
    'due': 'Due',
    'of': 'of',
    'uses': 'uses',
    'replaceBlade': 'Replace blade',
    'addTool': 'Add tool',
    'editTool': 'Edit tool',
    'deleteTool': 'Delete tool',
    'save': 'Save changes',
    'lastWeeks': 'Last 14 weeks',
    'consistency': 'Consistency',
    'sessions': 'sessions',
    'recent': 'Recent history',
    'noActivity': 'No activity yet',
    'noActivityText': 'Your shaves and replacements will appear here.',
    'shaved': 'shaved',
    'bladeReplaced': 'Blade replaced',
    'log': 'Log',
    'shave': 'shave',
    'chooseTool': 'Choose the tool used, estimate hair length, and rate the timing.',
    'confirm': 'Confirm shave',
    'cancel': 'Cancel',
    'setTool': 'Set a blade lifespan and identifying accent.',
    'name': 'Name',
    'maxUses': 'Maximum uses',
    'accent': 'Accent color',
    'add': 'Add tool',
    'toolType': 'Tool type',
    'razor': 'Razor',
    'trimmer': 'Trimmer',
    'toolPlaceholder': '',
    'ready': 'ready',
    'settings': 'Change language',
    'hairLength': 'Hair length',
    'timing': 'Was this shave timed well?',
    'early': 'Too early',
    'right': 'Just right',
    'late': 'Too late',
    'recommendation': 'Smart recommendation',
    'nextIn': 'Next shave in about',
    'days': 'days',
    'learning': 'The estimate improves with every shave.',
    'notifications': 'Enable Notifications',
    'notificationsDesc': 'Receive reminders for your next shave.',
    'notificationTime': 'Notification Time',
    'averageTime': 'Use Average Shave Time',
    'averageTimeDesc': 'Automatically adapt the reminder time to your historical shaving habits.',
    'againstTheGrain': 'Against the grain (closer shave)',
    'dataManagement': 'Data Management',
    'exportData': 'Share / Export Data',
    'exportDataDesc': 'Send via AirDrop, Nearby Share, or copy',
    'importData': 'Import Data',
    'importDataDesc': 'Paste data from another device',
    'pasteData': 'Paste your data here',
    'dataExported': 'Data ready to share/copy',
    'dataImported': 'Data imported successfully',
    'invalidData': 'Invalid data format',
    'dataInstructions': 'To transfer your data to a new device without the cloud:\n\n1. Tap Export on this device. You will get a text file/string. You can share it via AirDrop, Nearby Share, or copy it.\n2. On the new device, tap Import and paste the data.',
  },
  'el': {
    'personalCare': 'Προσωπική φροντίδα',
    'homeTitle': 'Περιποίηση',
    'gearTitle': 'Ανταλλακτικά',
    'statsTitle': 'Δραστηριότητα',
    'settingsTitle': 'Ρυθμίσεις',
    'welcome': 'Καλώς όρισες',
    'enterName': 'Πώς σε λένε;',
    'saveName': 'Συνέχεια',
    'bladeLife': 'Ζωή λεπίδας & ξύρισμα',
    'remaining': 'απομένει',
    'usesRemaining': 'χρήσεις απομένουν',
    'groomed': 'Ξυρισμένος',
    'bodyAverage': 'μέσος όρος σώματος',
    'addFirst': 'Πρόσθεσε το πρώτο ανταλλακτικό',
    'bodyMap': 'Χάρτης σώματος',
    'allZones': 'Όλα τα σημεία',
    'bodyQuestion': 'Ποια περιοχή ξυρίζουμε;',
    'front': 'Μπροστά',
    'back': 'Πίσω',
    'fresh': 'Πρόσφατα',
    'soon': 'Σύντομα',
    'due': 'Χρειάζεται',
    'of': 'από',
    'uses': 'χρήσεις',
    'replaceBlade': 'Αλλαγή λεπίδας',
    'addTool': 'Προσθήκη ανταλλακτικού',
    'editTool': 'Επεξεργασία ανταλλακτικού',
    'deleteTool': 'Διαγραφή ανταλλακτικού',
    'save': 'Αποθήκευση',
    'lastWeeks': 'Τελευταίες 14 εβδομάδες',
    'consistency': 'Συνέπεια',
    'sessions': 'συνεδρίες',
    'recent': 'Πρόσφατο ιστορικό',
    'noActivity': 'Καμία δραστηριότητα',
    'noActivityText': 'Τα ξυρίσματα και οι αλλαγές λεπίδας θα εμφανίζονται εδώ.',
    'shaved': 'ξυρίστηκε',
    'bladeReplaced': 'Αλλαγή λεπίδας',
    'log': 'Καταγραφή:',
    'shave': 'ξύρισμα',
    'chooseTool': 'Επίλεξε ανταλλακτικό, μήκος τρίχας και αν ο χρόνος ήταν σωστός.',
    'confirm': 'Επιβεβαίωση ξυρίσματος',
    'cancel': 'Ακύρωση',
    'setTool': 'Όρισε τη διάρκεια ζωής και το χρώμα του ανταλλακτικού.',
    'name': 'Όνομα',
    'maxUses': 'Μέγιστες χρήσεις',
    'accent': 'Χρώμα',
    'add': 'Προσθήκη',
    'toolType': 'Τύπος εργαλείου',
    'razor': 'Ξυράφι',
    'trimmer': 'Trimmer (Κοπτική)',
    'toolPlaceholder': '',
    'ready': 'έτοιμο',
    'settings': 'Αλλαγή γλώσσας',
    'hairLength': 'Μήκος τρίχας',
    'timing': 'Ήταν σωστή η στιγμή;',
    'early': 'Πολύ νωρίς',
    'right': 'Ακριβώς σωστά',
    'late': 'Πολύ αργά',
    'recommendation': 'Έξυπνη πρόταση',
    'nextIn': 'Επόμενο ξύρισμα σε περίπου',
    'days': 'ημέρες',
    'learning': 'Η πρόβλεψη βελτιώνεται με κάθε ξύρισμα.',
    'notifications': 'Ενεργοποίηση Ειδοποιήσεων',
    'notificationsDesc': 'Λάβε υπενθυμίσεις όταν πρέπει να ξυριστείς.',
    'notificationTime': 'Ώρα Ειδοποίησης',
    'averageTime': 'Χρήση Μέσου Όρου Ώρας',
    'averageTimeDesc': 'Προσαρμογή της ώρας βάσει των συνηθειών σου από προηγούμενα ξυρίσματα.',
    'againstTheGrain': 'Κόντρα (βαθύτερο ξύρισμα)',
    'dataManagement': 'Διαχείριση Δεδομένων',
    'exportData': 'Διαμοιρασμός / Εξαγωγή',
    'exportDataDesc': 'Αποστολή με Nearby Share, AirDrop ή αντιγραφή',
    'importData': 'Εισαγωγή Δεδομένων',
    'importDataDesc': 'Επικόλληση από άλλη συσκευή',
    'pasteData': 'Επικόλληση δεδομένων εδώ',
    'dataExported': 'Τα δεδομένα είναι έτοιμα',
    'dataImported': 'Επιτυχής εισαγωγή!',
    'invalidData': 'Μη έγκυρη μορφή δεδομένων',
    'dataInstructions': 'Για μεταφορά σε νέα συσκευή (χωρίς cloud):\n\n1. Πάτα Εξαγωγή (Export) σε αυτό το κινητό. Μπορείς να τα στείλεις με Nearby Share, AirDrop, ή να κάνεις αντιγραφή τον κώδικα JSON.\n2. Στο νέο κινητό, πάτα Εισαγωγή (Import) και κάνε επικόλληση (Paste) τα δεδομένα.',
  }
};

const Map<String, Map<String, String>> zoneNames = {
  'scalp': {'en': 'Scalp', 'el': 'Κεφάλι'},
  'face': {'en': 'Face', 'el': 'Πρόσωπο'},
  'neck': {'en': 'Neck', 'el': 'Λαιμός'},
  'armpits': {'en': 'Armpits', 'el': 'Μασχάλες'},
  'chest': {'en': 'Chest', 'el': 'Στήθος'},
  'abdomen': {'en': 'Abdomen', 'el': 'Κοιλιά'},
  'arms': {'en': 'Arms', 'el': 'Χέρια'},
  'hands': {'en': 'Hands', 'el': 'Παλάμες'},
  'groin': {'en': 'Groin', 'el': 'Βουβωνική χώρα'},
  'genitals': {'en': 'Genitals', 'el': 'Γεννητικά όργανα'},
  'legs': {'en': 'Legs', 'el': 'Πόδια'},
  'feet': {'en': 'Feet', 'el': 'Πέλματα'},
  'back': {'en': 'Back', 'el': 'Πλάτη'},
  'buttocks': {'en': 'Buttocks', 'el': 'Γλουτοί'},
  'anus': {'en': 'Anus', 'el': 'Πρωκτός'},
};
